siren_proj/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from siren_proj import views
from siren_proj.user import urls as user_urls
from siren_proj.video import urls as video_urls

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^user/', include(user_urls, namespace='user')),
    url(r'^video/', include(video_urls, namespace='video')),
    url(r'^admin/', include(admin.site.urls))


]

siren_proj/user/urls.py
from django.conf.urls import url

from siren_proj.user import views

urlpatterns = [

    url(r'^registration/$', views.registration, name='registration'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^change_password/$', views.change_password, name='change_password'),
    url(r'^profile/$', views.profile, name='profile'),

]

siren_proj/video/urls.py
from django.conf.urls import url

from siren_proj.video import views

urlpatterns = [

    url(r'^tv_show/(?P<pk>[0-9]+)/$', views.tv_show_view, name='tv_show'),
    url(r'^tv_show/foreign/$', views.filter_serials_foreign, name='foreign'),
    url(r'^tv_show/russian/$', views.filter_serials_russian, name='russian'),
    url(r'^tv_show/turkish/$', views.filter_serials_turkish, name='turkish'),
    url(r'^add/(?P<pk>[0-9]+)/$', views.subscribe, name='add'),
    url(r'^unsubscribe/(?P<pk>[0-9]+)/$', views.unsubscribe, name='unsubscribe'),
    url(r'^searching_result/$', views.search, name='search'),
    url(r'^main/$', views.main, name='main')

   ]

siren_proj/models.py
from django.contrib import admin
from django.db import models
from django.contrib.auth.models import AbstractBaseUser
from datetime import datetime, timedelta

from siren_proj.managers import UserManager


class User(AbstractBaseUser):
    username = models.CharField(max_length=50)
    login = models.CharField(max_length=50, unique=True)
    mail_address = models.EmailField()
    password = models.CharField(max_length=49)

    objects = UserManager()

    REQUIRED_FIELDS = ('username',)
    USERNAME_FIELD = 'login'

    class Meta:
        db_table = 'user'

    def __str__(self):
        return self.username

    def get_full_name(self):
        pass

    def get_short_name(self):
        return self.username


class Video(models.Model):
    name = models.CharField(max_length=100)
    year_of_issue = models.IntegerField()
    country = models.CharField(max_length=100)
    genre = models.CharField(max_length=100, null=True, blank=True)
    duration = models.IntegerField(null=True, blank=True)
    premiere = models.CharField(max_length=50, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    photo = models.CharField(max_length=100)
    type = models.IntegerField()
    season = models.SmallIntegerField(null=True, blank=True)
    last_episode = models.CharField(max_length=10, null=True, blank=True)
    label = models.CharField(max_length=30, null=True, blank=True)

    class Meta:
        db_table = 'video'

    def __str__(self):
        return self.name


class UserSubscription(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    video = models.ForeignKey(Video, on_delete=models.CASCADE)

    class Meta:
        db_table = 'user_subscription'

    def __str__(self):
        return '{}, {}'.format(self.user, self.video)


class Website(models.Model):
    title = models.TextField()
    video = models.ForeignKey(Video, on_delete=models.CASCADE)
    update_date = models.CharField(max_length=50)
    link_to_watch_online = models.URLField()
    quality = models.CharField(max_length=50, null=True, blank=True)
    translation = models.CharField(max_length=100, null=True, blank=True)

    class Meta:
        db_table = 'website'

    def __str__(self):
        return '{}'.format(self.title)


class Session(models.Model):
    user = models.ForeignKey(User)
    token = models.CharField(max_length=36)
    date_expired = models.DateTimeField(default=datetime.now() + timedelta(days=7))

    class Meta:
        db_table = 'session'

admin.site.register(User)
admin.site.register(Video)
admin.site.register(UserSubscription)
admin.site.register(Website)

siren_proj/user/forms.py
from django import forms
from django.contrib.auth.hashers import check_password
from siren_proj.models import User


class RegistrationForm(forms.Form):
    username = forms.CharField(max_length=50, initial='')
    mail_address = forms.EmailField(initial='')
    login = forms.CharField(max_length=50, initial='')
    password = forms.CharField(min_length=6, initial='')

    def clean_login(self):
        login = self.cleaned_data['login']
        if User.objects.filter(login=login).first():
            raise forms.ValidationError('login %s already exist' % login)
        return login


class LoginForm(forms.Form):
    login = forms.CharField(max_length=50, initial='')
    password = forms.CharField(min_length=6, initial='')

    def clean(self):
        cleaned_data = super().clean()
        login = cleaned_data['login']
        password = cleaned_data['password']
        self.user = User.objects.filter(login=login).first()
        if not (self.user and check_password(password, self.user.password)):
            raise forms.ValidationError('Incorrect login or password')
        return login


class PasswordChangeForm(forms.Form):
    new_password = forms.CharField(min_length=6, initial='')
    reenter_password = forms.CharField(min_length=6, initial='')

    def clean(self):
        cleaned_data = super().clean()
        new_password = cleaned_data['new_password']
        reenter_password = cleaned_data['reenter_password']
        if new_password != reenter_password:
            raise forms.ValidationError('reenter password not equal new password')
        else:
            return cleaned_data

siren_proj/video/forms.py
from django import forms


class SearchForm(forms.Form):
    video_title = forms.CharField(max_length=50, initial='')

    def clean(self):
        cleaned_data = super().clean()
        video_title = cleaned_data['video_title']
        return cleaned_data

siren_proj/user/views.py
from django.shortcuts import render, redirect
import uuid
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from siren_proj import models
from siren_proj.user.forms import RegistrationForm, LoginForm, PasswordChangeForm
from siren_proj.models import User, Session, Video


def index(request):
    videos = models.Video.objects.all()
    return render(request, 'index.html', {'videos': videos})


def registration(request):
    if request.method == 'POST':
        form = RegistrationForm(data=request.POST)
        if form.is_valid():
            if not User.objects.registration(
                form.cleaned_data['login'],
                form.cleaned_data['password'],
                form.cleaned_data['username'],
                form.cleaned_data['mail_address']
            ):
                pass
            return redirect('user:login')
    else:
        form = RegistrationForm()
    return render(request, 'user/registration.html',
                  context={'form': form})


def login(request):
    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            session = Session.objects.create(user=form.user, token=uuid.uuid4())
            response = redirect('user:profile')
            response.set_cookie('user-session', session.token,
                                expires=session.date_expired)
            return response
    else:
        form = LoginForm()

    return render(request, 'user/login.html', context={'form': form})


def logout(request):
    user_session = request.COOKIES['user-session']
    session = Session.objects.filter(token=user_session).last()
    if session.delete():
        return redirect('user:login')
    else:
        print("err")


def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST)
        if form.is_valid():
            new_pass = form.cleaned_data['new_password']
            User.objects.change_password(new_pass, request.user.id)
            return redirect('user:login')
    else:
        form = PasswordChangeForm()
    return render(request, 'user/change_password.html', context={'form': form})


def profile(request):
    videos = Video.objects.filter(usersubscription__user_id=request.user.id).order_by('year_of_issue').reverse()
    info_web = models.Website.objects.all()
    paginator = Paginator(videos, 9)
    page = request.GET.get('page')
    try:
        videos = paginator.page(page)
    except PageNotAnInteger:
        videos = paginator.page(1)
    except EmptyPage:
        videos = paginator.page(paginator.num_pages)

    return render(request, 'user/profile.html', {'videos': videos,
                                                 'info_web': info_web})

siren_proj/video/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from siren_proj import models
from siren_proj.video.forms import SearchForm
from siren_proj import settings


def get_subscriptions(request):
    subscriptions_query = models.UserSubscription.objects.values()
    subscriptions = []
    for sub in subscriptions_query:
        if sub['user_id'] == request.user.id:
            subscriptions.append(sub['video_id'])
    return subscriptions


def tv_show_view(request, pk):
    tv_shows = models.Video.objects.filter(id=pk)
    info_web = models.Website.objects.filter(video_id=pk)
    subscriptions = get_subscriptions(request)
    return render(request, 'video/tv_show.html', {'tv_shows': tv_shows,
                                                  'subscriptions': subscriptions,
                                                  'info_web': info_web})


def main(request):
    videos = models.Video.objects.all().\
        order_by('year_of_issue').reverse()
    subscriptions = get_subscriptions(request)
    info_web = models.Website.objects.all()
    paginator = Paginator(videos, 9)
    page = request.GET.get('page')
    try:
        videos = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        videos = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        videos = paginator.page(paginator.num_pages)

    return render(request, 'video/main.html', context={'videos': videos,
                                                       'subscriptions': subscriptions,
                                                       'info_web': info_web
                                                      })


def subscribe(request, pk):
    referer = request.META.get('HTTP_REFERER')
    is_user_subscribe = models.UserSubscription.objects.filter(user_id=request.user.id, video_id=pk).first()
    if is_user_subscribe:
        pass
    else:
        user_subscribe = models.UserSubscription.objects.create(user_id=request.user.id,
                                                                video_id=pk)
        user_subscribe.save()
    return redirect(referer)


def unsubscribe(request, pk):
    referer = request.META.get('HTTP_REFERER')
    print(referer)
    user_subscribe = models.UserSubscription.objects.filter(user_id=request.user.id,
                                                            video_id=pk).first()
    if user_subscribe:
        models.UserSubscription.objects.filter(user_id=request.user.id,
                                               video_id=pk).delete()
    return redirect(referer)


def search(request, ):
    referer = request.META.get('HTTP_REFERER')
    form = SearchForm(data=request.POST)
    subscriptions = models.UserSubscription.objects.filter(user_id=request.user.id)
    info_web = models.Website.objects.all()
    try:
        if form.is_valid():
            title = form.cleaned_data['video_title']
            videos = models.Video.objects.filter(name__icontains=title).order_by('year_of_issue').reverse()
            return render(request, 'video/searching_result.html', {'videos': videos,
                                                                   'subscriptions': subscriptions,
                                                                   'info_web': info_web,
                                                                   })
    except KeyError:
        if request.get_full_path() in referer:
            return redirect('video:main')
        else:
            return redirect(referer)


def filter_serials_foreign(request):
    videos = models.Video.objects.filter(type=1).exclude(country='Россия').exclude(
        country='Турция').distinct('name')
    subscriptions = get_subscriptions(request)
    info_web = models.Website.objects.all()
    paginator = Paginator(videos, 9)
    page = request.GET.get('page')
    try:
        videos = paginator.page(page)
    except PageNotAnInteger:
        videos = paginator.page(1)
    except EmptyPage:
        videos = paginator.page(paginator.num_pages)

    return render(request, 'video/main.html', {'videos': videos,
                                               'subscriptions': subscriptions,
                                               'info_web': info_web})


def filter_serials_russian(request):
    videos = models.Video.objects.filter(type=1, country='Россия').distinct('name')
    subscriptions = get_subscriptions(request)
    info_web = models.Website.objects.all()
    paginator = Paginator(videos, 9)
    page = request.GET.get('page')
    try:
        videos = paginator.page(page)
    except PageNotAnInteger:
        videos = paginator.page(1)
    except EmptyPage:
        videos = paginator.page(paginator.num_pages)

    return render(request, 'video/main.html', {'videos': videos,
                                               'subscriptions': subscriptions,
                                               'info_web': info_web})


def filter_serials_turkish(request):
    videos = models.Video.objects.filter(type=1, country='Турция').distinct('name')
    subscriptions = get_subscriptions(request)
    info_web = models.Website.objects.all()
    paginator = Paginator(videos, 9)
    page = request.GET.get('page')
    try:
        videos = paginator.page(page)
    except PageNotAnInteger:
        videos = paginator.page(1)
    except EmptyPage:
        videos = paginator.page(paginator.num_pages)

    return render(request, 'video/main.html', {'videos': videos,
                                               'subscriptions': subscriptions,
                                               'info_web': info_web})

siren_proj/views.py
from django.shortcuts import redirect


def index(request):
    return redirect('video:main')

siren_proj/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Siren</title>

  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="/static/base.css">
<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


</head>
<body>

<div class="navbar-wrapper">
    <div class="container-fluid">
        <nav class="navbar navbar-fixed-top">
            <div class="container_bar">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand">Siren</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="{% url 'video:main' %}">Home</a></li>

                        <li class=" dropdown"><a href="#" class="dropdown-toggle active" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> Сериалы <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li class=""><a href="{% url 'video:russian' %}">Русские</a></li>
                                <li class=""><a href="{% url 'video:foreign' %}">Зарубежные</a>
                                <li class=""><a href="{% url 'video:turkish' %}">Турецкие</a></li>
                            </ul>
                        </li>
                    </ul>
                    <ul class="nav navbar-nav">
                       <li class="">
                            <div class="lighter">
                                    <form class="" method="post" action="{% url 'video:search' %}">
                                        {% csrf_token %}
                                            <span><input type="text" class="search rounded" name="video_title"
                                                         id="video_title" placeholder="Искать..."
                                                         value="{{ form.video_title.value }}">
                                            </span>

                                                <button class="button blue_alt" type="submit">Go</button>

                                    </form>
                            </div>
                        </li>
                    </ul>
                    <ul class="nav navbar-nav pull-right">
                        {% if user.is_authenticated %}
                        <li class=" dropdown"><a href="#" class="dropdown-toggle active" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Вы вошли как {{ user.login }} <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li class=""><a href="{% url 'user:profile' %}">Мои сериалы</a></li>
                                <li class=""><a href="{% url 'user:change_password' %}">Сменить пароль</a>
                                <li class=""><a href="{% url 'user:logout' %}">Выйти</a></li>

                            </ul>
                        {% endif %}
                        {% if not user.is_authenticated %}
                            <li class=""><a href="{% url 'user:registration' %}">Регистрация</a></li>
                            <li class=""><a href="{% url 'user:login' %}">Войти</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
{% block content %}
{% endblock %}
</div>
</div>
</body>
</html>

siren_proj/templates/index.html
{% extends "base.html" %}

{% block content %}

    {% if form.errors %}
        {{ form.errors }}}
    {% endif %}


{% endblock %}